### ISSUE TITLE
Design and implement Splash Screen for the app.

### ISSUE THREAD

**Issue by Rits1272** [Rits1272/Memegram#1]
Splash screen is basically an introductory screen shown for few seconds at starting of the app. The boilerplate code for the splash screen is already implemented. Your task would be to make Splash Screen attractive as this would be the starting point of our application.

Presently, it looks like this: 
![WhatsApp Image 2020-12-05 at 22 22 12](https://user-images.githubusercontent.com/44135362/101258615-a2e52a80-3749-11eb-9db3-85accc3eb24b.jpeg)

As a resource, you can check out my first part of article on the [same
](https://medium.com/nerd-for-tech/making-drawer-navigator-and-a-splash-screen-on-your-react-native-app-2fb561ee17f1?source=friends_link&sk=5bb3bfacf7c18cd40ad2c745100c95bb)

**Comment by lopeselio** [comment]
can I work on this ?

**Comment by Rits1272** [comment]
Yeah sure @lopeselio

**Comment by lopeselio** [comment]
<img width="2981" alt="Asset 1@2x" src="https://user-images.githubusercontent.com/43913734/102251462-d898c900-3f2a-11eb-95e2-f043410c7278.png">
 How about this for the splash screen ?

**Comment by Rits1272** [comment]
Great! Make a PR for the same

**Comment by lopeselio** [comment]
Hey @Rits1272 , let me know if there are any changes. Cheers!
![image](https://user-images.githubusercontent.com/43913734/102310489-12041f80-3f91-11eb-94b4-12658657e0a3.png)
